# This workflow will setup .NET and MATLAB on the host machine
name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    strategy:
      matrix:
        dotnet-version: [ '6.0.x', '8.0.x' ]
        matlab-version: [ 'latest' ]
        os: [ 'ubuntu-latest' ]

    runs-on: ${{ matrix.ubuntu-latest }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Display .NET version
      run: dotnet --version
      
    - name: Setup MATLAB
      uses: matlab-actions/setup-matlab@v2
      with:
        release: ${{ matrix.matlab-version }}
        cache: true
