# This workflow will setup .NET and MATLAB on the host machine
name: Run MATLAB Engine for .NET Examples

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-examples:
    strategy:
      matrix:
        os: [ 'windows-latest', 'ubuntu-latest', 'macos-latest' ]

    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Setup Latest MATLAB
      uses: matlab-actions/setup-matlab@v2
      with:
        release: R2025a

    # Get matlabroot
    - name: Get matlabroot
      run: echo "matlabroot="$(matlab -batch "disp(matlabroot)")"" >> $GITHUB_OUTPUT
      
    # Latest .NET SDK is already installed on GitHub runners

    - name: Build and Run .NET Code
      run: dotnet run --project Examples/Examples.csproj /p:matlabroot="$matlabroot"
